#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libuv
Version  : 1.22.0
Release  : 4
URL      : https://github.com/libuv/libuv/archive/v1.22.0.tar.gz
Source0  : https://github.com/libuv/libuv/archive/v1.22.0.tar.gz
Summary  : multi-platform support library with a focus on asynchronous I/O.
Group    : Development/Tools
License  : CC-BY-4.0 MIT NCSA
Requires: libuv-lib
Requires: libuv-license

%description
![libuv][libuv_banner]
## Overview
libuv is a multi-platform support library with a focus on asynchronous I/O. It
was primarily developed for use by [Node.js][], but it's also
used by [Luvit](http://luvit.io/), [Julia](http://julialang.org/),
[pyuv](https://github.com/saghul/pyuv), and [others](https://github.com/libuv/libuv/wiki/Projects-that-use-libuv).

%package dev
Summary: dev components for the libuv package.
Group: Development
Requires: libuv-lib
Provides: libuv-devel

%description dev
dev components for the libuv package.


%package lib
Summary: lib components for the libuv package.
Group: Libraries
Requires: libuv-license

%description lib
lib components for the libuv package.


%package license
Summary: license components for the libuv package.
Group: Default

%description license
license components for the libuv package.


%prep
%setup -q -n libuv-1.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533059295
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533059295
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libuv
cp LICENSE %{buildroot}/usr/share/doc/libuv/LICENSE
cp LICENSE-docs %{buildroot}/usr/share/doc/libuv/LICENSE-docs
cp samples/socks5-proxy/LICENSE %{buildroot}/usr/share/doc/libuv/samples_socks5-proxy_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/uv/errno.h
/usr/include/uv/linux.h
/usr/include/uv/threadpool.h
/usr/include/uv/unix.h
/usr/include/uv/version.h
/usr/lib64/libuv.so
/usr/lib64/pkgconfig/libuv.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libuv.so.1
/usr/lib64/libuv.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libuv/LICENSE
/usr/share/doc/libuv/LICENSE-docs
/usr/share/doc/libuv/samples_socks5-proxy_LICENSE
